require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe LinksController do
  before do 
    @url = "http://www.google.com"
  end

  def mock_link(stubs={})
    @mock_link ||= mock_model(Link, stubs).as_null_object
  end

  describe "GET show" do
    it "assigns the requested link as @link" do
      mock_link.stub(:url) { mock_model(Url, :original => @url)}
      Link.stub(:find).with("37") { mock_link }
      get :show, :id => "37"
      response.should redirect_to(@url)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created link as @link" do
        Link.stub(:shorten).with(@url, nil) { mock_link(:save => true) }
        post :create, :original => @url, :custom => ""
        assigns(:link).should be(mock_link)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved link as @link" do
        Link.stub(:shorten).with(@url, nil) { mock_link(:save => false) }
        post :create, :original => @url, :custom => ""
        assigns(:link).should be(mock_link)
      end
    end
  end
end
